### ISSUE TITLE
Remove Album Art

### ISSUE THREAD

**Issue by Nightshade935** [minermonster19/SpotifyControls#1]
I really enjoy using this plugin however I really wish there would be an option for not to display the album art of the song and just the name of it. This is because it takes too much space when the album art is showing, and hides a lot of your direct messages, causing you to have to scroll more. I would really appreciate if this feature was added, or if you could tell me so I could remove that part of the code myself. Thanks!

**Comment by minermonster19** [comment]
If you want a smaller player, I’d suggest checking out the original plugin by mwittrien: 
[https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/SpotifyControls](https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/SpotifyControls)

This is how the original plugin currently looks:
![cover](https://user-images.githubusercontent.com/26031783/110416913-8adfb880-8062-11eb-93a9-0ee9a86e30c4.png)

If you really want just the text, I can check to implement it as a toggle through the plugin settings in the next update.
